#controllers:
#    resource:
#        path: ../src/Controller/
#        namespace: App\IndexController
#    type: attribute

#homepage:
#    path: / 
#    controller: App\Controller\NewController::home

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


